// This file is auto-generated by TanStack Router

import { FileRoute, lazyRouteComponent } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PanelImport } from './routes/panel'
import { Route as NotFoundImport } from './routes/not-found'
import { Route as LayoutImport } from './routes/_layout'
import { Route as PanelEmployeeImport } from './routes/panel.employee'

// Create Virtual Routes

const LayoutIndexComponentImport = new FileRoute('/_layout/').createRoute()
const LayoutSearchAnimeCategoryComponentImport = new FileRoute(
  '/_layout/search/anime/$category',
).createRoute()
const LayoutAnimeAnimeIdAnimeSlugComponentImport = new FileRoute(
  '/_layout/anime/$animeId/$animeSlug',
).createRoute()
const LayoutSearchAnimeIndexComponentImport = new FileRoute(
  '/_layout/search/anime/',
).createRoute()

// Create/Update Routes

const PanelRoute = PanelImport.update({
  path: '/panel',
  getParentRoute: () => rootRoute,
} as any)

const NotFoundRoute = NotFoundImport.update({
  path: '/not-found',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexComponentRoute = LayoutIndexComponentImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/_layout/index.component'),
    'component',
  ),
})

const PanelEmployeeRoute = PanelEmployeeImport.update({
  path: '/employee',
  getParentRoute: () => PanelRoute,
} as any)

const LayoutSearchAnimeCategoryComponentRoute =
  LayoutSearchAnimeCategoryComponentImport.update({
    path: '/search/anime/$category',
    getParentRoute: () => LayoutRoute,
  } as any).update({
    component: lazyRouteComponent(
      () => import('./routes/_layout/search.anime.$category/component'),
      'component',
    ),
  })

const LayoutAnimeAnimeIdAnimeSlugComponentRoute =
  LayoutAnimeAnimeIdAnimeSlugComponentImport.update({
    path: '/anime/$animeId/$animeSlug',
    getParentRoute: () => LayoutRoute,
  } as any).update({
    component: lazyRouteComponent(
      () => import('./routes/_layout/anime.$animeId.$animeSlug/component'),
      'component',
    ),
  })

const LayoutSearchAnimeIndexComponentRoute =
  LayoutSearchAnimeIndexComponentImport.update({
    path: '/search/anime/',
    getParentRoute: () => LayoutRoute,
  } as any).update({
    component: lazyRouteComponent(
      () => import('./routes/_layout/search.anime.index/component'),
      'component',
    ),
  })

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/not-found': {
      preLoaderRoute: typeof NotFoundImport
      parentRoute: typeof rootRoute
    }
    '/panel': {
      preLoaderRoute: typeof PanelImport
      parentRoute: typeof rootRoute
    }
    '/panel/employee': {
      preLoaderRoute: typeof PanelEmployeeImport
      parentRoute: typeof PanelImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexComponentImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/search/anime/': {
      preLoaderRoute: typeof LayoutSearchAnimeIndexComponentImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/anime/$animeId/$animeSlug': {
      preLoaderRoute: typeof LayoutAnimeAnimeIdAnimeSlugComponentImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/search/anime/$category': {
      preLoaderRoute: typeof LayoutSearchAnimeCategoryComponentImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutIndexComponentRoute,
    LayoutSearchAnimeIndexComponentRoute,
    LayoutAnimeAnimeIdAnimeSlugComponentRoute,
    LayoutSearchAnimeCategoryComponentRoute,
  ]),
  NotFoundRoute,
  PanelRoute.addChildren([PanelEmployeeRoute]),
])
